apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xtlmaq27m-nodejs
  janus-idp.io/tekton: xtlmaq27m-nodejs
  backstage.io/kubernetes-id: xtlmaq27m-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: xtlmaq27m-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
